spring:
  application:
    name: payday-trade

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/payday_trade
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: mm4846236@gmail.com
    password: rrhmlsgorpzppzoe
    port: 587
    properties:
      mail:
        smtp:
          debug: true
          writetimeout: 5000
          timeout: 5000
          connectiontimeout: 5000
          auth: true
          starttls:
            required: true
            enable: true

security:
  authentication:
    jwt:
      base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
      token-validity-in-seconds: 2592000
